---
# Unattended Upgrades Policy (Hypervisors require manual/coordinated maintenance)
unattended_upgrades_automatic_reboot: false
unattended_upgrades_automatic_reboot_time: "03:30"

proxmox_backup_mgmt_enabled: true
proxmox_backup_jobs:
  - id: "haos-daily-pbs"
    name: "Home Assistant Daily"
    node: "proxmox1"
    schedule: "04:00"
    storage: "pbs01"
    mode: "snapshot"
    vmid: "107"
    notes_template: !unsafe "{{guestname}}"
    enabled: true
    mailto: "root@home.arpa"
    mailnotification: "failure"
  - id: "lyrion-daily-pbs"
    name: "Lyrion Daily"
    node: "pve2"
    schedule: "02:00"
    storage: "pbs01"
    mode: "snapshot"
    vmid: "113"
    notes_template: !unsafe "{{guestname}}"
    enabled: true
    mailto: "root@home.arpa"
    mailnotification: "failure"
