---
ntfy_base_url: "https://ntfy-lxc-01.van-bee.ts.net"
ntfy_listen_http: ":80"
ntfy_upstream_base_url: "https://ntfy.sh"
ntfy_auth_default_access: "deny-all"
ntfy_enable_tailscale: true

ntfy_auth_users: []
ntfy_auth_tokens: []
ntfy_auth_access:
  - "publisher:lab-*:wo"
  - "publisher:desktop-will:wo"
  - "publisher:desktop-all:wo"
  - "hass:lab-*:rw"
  - "will-phone:lab-critical:ro"
  - "will-phone:lab-warning:ro"
  - "will-desktop:lab-critical:ro"
  - "will-desktop:lab-warning:ro"
  - "will-desktop:desktop-will:ro"
  - "will-desktop:desktop-all:ro"
  - "household-desktop:lab-critical:ro"
  - "household-desktop:lab-warning:ro"
  - "household-desktop:desktop-all:ro"
