---
# ==============================================================================
# Filename:       roles/browser_baseline/tasks/main.yml
# Version:        1.0
# Author:         Pops AI / Gemini
# Last Modified:  2026-08-31
# Trac Tickets:   #2783, #4407, #4408, #4409, #4410, #4411
#
# Purpose:
#     Main task list for the browser_baseline role. Deploys Google Chrome,
#     Firefox, Dillo, and system enterprise policies for extensions.
# ==============================================================================

- name: Apply Google Chrome baseline
  ansible.builtin.include_tasks: chrome.yml
  when: browser_baseline_manage_chrome | bool

- name: Apply Mozilla Firefox baseline
  ansible.builtin.include_tasks: firefox.yml
  when: browser_baseline_manage_firefox | bool

- name: Apply Dillo browser baseline
  ansible.builtin.include_tasks: dillo.yml
  when: browser_baseline_manage_dillo | bool
