#!/usr/bin/env python3
"""
Filename:       test_create_wwos_page.py
Version:        1.0
Last Modified:  2026-09-12
Context:        WWOS Page Creation & Formatting (Trac #4601)

Secrets:
    None - tests pure wikitext construction and category parsing logic.
"""
import sys
import unittest
from pathlib import Path

# Add project root and scripts directory
PROJECT_ROOT = Path(__file__).parents[1]
sys.path.insert(0, str(PROJECT_ROOT))
from scripts import create_wwos_page as cwp


class CreateWwosPageContentTests(unittest.TestCase):
    def test_therapy_south_full_content_preserved_without_duplication(self):
        """Trac #4601: Complete page content with existing bop and categories is not duplicated."""
        content = (
            "'''Therapy South''' is a physical therapy clinic with a location in Columbus, Georgia, "
            "next to a Dunkin' Donuts. Jen Taff has received pelvic floor physical therapy evaluation "
            "and treatment there.<ref>AI-generated by Claude Code on 2026-09-12</ref>\n\n"
            "== Trac ==\n"
            "* '''[http://trac.gafla.us.com/ticket/4405 trac #4405 \"Health: Jen — CC: Pelvic floor physical therapy (Therapy South)\"]'''\n\n"
            "{{bop}}\n"
            "[[Category:Physical therapy]]\n"
            "[[Category:Healthcare providers]]\n"
            "[[Category:Columbus, Georgia]]\n"
        )
        # Calling with categories parameter matching the existing categories
        result = cwp.build_page_content(
            "Therapy South",
            "Physical therapy, Healthcare providers, Columbus, Georgia",
            content
        )
        self.assertEqual(result.strip(), content.strip())
        self.assertEqual(result.count("'''Therapy South'''"), 1)
        self.assertEqual(result.count("{{bop}}"), 1)
        self.assertNotIn("{{baseOfPage}}", result)
        self.assertIn("[[Category:Columbus, Georgia]]", result)
        self.assertNotIn("[[Category:Columbus]]\n", result)
        self.assertNotIn("[[Category:Georgia]]\n", result)

    def test_lead_opener_no_standalone_title(self):
        """Trac #4601: Content starting with a bold lead paragraph does not prepend a standalone bold title."""
        content = "'''Direct attach copper''' is a form of high speed cable."
        result = cwp.build_page_content("Direct attach copper", "Cables", content)
        self.assertFalse(result.startswith("'''Direct attach copper'''\n\n'''Direct attach copper'''"))
        self.assertTrue(result.startswith("'''Direct attach copper''' is a form of high speed cable."))

    def test_unbolded_lead_woven_in(self):
        """Content starting with unbolded title has title bolded into the sentence."""
        content = "Direct attach copper is a form of high speed cable."
        result = cwp.build_page_content("Direct attach copper", "Cables", content)
        self.assertTrue(result.startswith("'''Direct attach copper''' is a form of high speed cable."))

    def test_hatnote_and_template_openers(self):
        """Content starting with disambiguation hatnotes or templates preserves them as the opener."""
        disambig = "''Did you mean [[Other Page]]?''\n\n'''Main Subject''' is an article."
        result = cwp.build_page_content("Main Subject", "General", disambig)
        self.assertTrue(result.startswith("''Did you mean [[Other Page]]?''"))

        tmpl = "{{Lowercase}}\n'''tmux''' is a terminal multiplexer."
        result_tmpl = cwp.build_page_content("tmux", "Terminal multiplexers", tmpl)
        self.assertTrue(result_tmpl.startswith("{{Lowercase}}"))

    def test_category_page_formatting(self):
        """Category: pages must not have a bold title prepended or {{bop}} added."""
        result = cwp.build_page_content(
            "Category:Physical therapy",
            "Healthcare",
            "Articles relating to physical therapy clinics and practitioners."
        )
        self.assertNotIn("'''Category:Physical therapy'''", result)
        self.assertNotIn("{{bop}}", result)
        self.assertNotIn("{{baseOfPage}}", result)
        self.assertIn("[[Category:Healthcare]]", result)

    def test_redirect_page_verbatim(self):
        """Redirect pages are returned verbatim without titles, bop, or categories."""
        redirect = "#REDIRECT [[Therapy South]]"
        result = cwp.build_page_content("TherapySouth", "General", redirect)
        self.assertEqual(result, redirect)

    def test_module_page_verbatim(self):
        """Module: pages (Scribunto Lua) are returned verbatim without wikitext wrappers."""
        lua_code = "local p = {}\nfunction p.hello() return 'hello' end\nreturn p"
        result = cwp.build_page_content("Module:Hello", "Lua", lua_code)
        self.assertEqual(result, lua_code)

    def test_legacy_baseofpage_normalization(self):
        """Legacy {{baseOfPage}} in input is normalized to {{bop}} without duplicating."""
        content = "'''Legacy Page''' is old.\n\n{{baseOfPage}}\n[[Category:Old]]\n"
        result = cwp.build_page_content("Legacy Page", "Old", content)
        self.assertNotIn("{{baseOfPage}}", result)
        self.assertEqual(result.count("{{bop}}"), 1)
        self.assertEqual(result.count("[[Category:Old]]"), 1)

    def test_missing_bop_inserted_above_existing_categories(self):
        """When categories are present in content without {{bop}}, {{bop}} is inserted directly above them."""
        content = "'''Simple Page''' is a simple page.\n\n[[Category:Simple]]\n"
        result = cwp.build_page_content("Simple Page", "", content)
        self.assertEqual(result.count("{{bop}}"), 1)
        self.assertIn("{{bop}}\n[[Category:Simple]]", result)

    def test_category_parsing_and_healing(self):
        """Trac #4601: Category parsing handles lists, delimiters, quotes, and state comma healing."""
        # List of categories preserves comma
        cats_list = ["Physical therapy", "Healthcare providers", "Columbus, Georgia"]
        self.assertEqual(cwp.parse_categories(cats_list), cats_list)

        # Semicolon delimited
        semi = "Physical therapy; Healthcare providers; Columbus, Georgia"
        self.assertEqual(cwp.parse_categories(semi), cats_list)

        # Pipe delimited
        pipe = "Physical therapy|Healthcare providers|Columbus, Georgia"
        self.assertEqual(cwp.parse_categories(pipe), cats_list)

        # Quoted CSV
        quoted = 'Physical therapy, Healthcare providers, "Columbus, Georgia"'
        self.assertEqual(cwp.parse_categories(quoted), cats_list)

        # Unquoted comma-split with recognized US state/geographic suffix
        unquoted = "Physical therapy, Healthcare providers, Columbus, Georgia"
        self.assertEqual(cwp.parse_categories(unquoted), cats_list)


if __name__ == "__main__":
    unittest.main()
