---
# handlers file for trac_server
- name: Restart Apache
  ansible.builtin.systemd:
    name: apache2
    state: restarted

- name: Reload Apache
  ansible.builtin.systemd:
    name: apache2
    state: reloaded
