---
mail_repository_catchall_user: "catchall"
mail_repository_catchall_password: "password123" # User should change this or use Vault
mail_repository_mailbox_limit: 0
mail_repository_trusted_networks: "127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128 192.168.0.0/24"
mail_repository_domain: "home.arpa"

# Optional external SMTP relaying
mail_repository_relay_enabled: false
mail_repository_relay_host: "smtp.gmail.com"
mail_repository_relay_port: 587
mail_repository_relay_user: ""
mail_repository_relay_password: ""
