---
unattended_upgrades_allowed_origins:
  - "${distro_id}:${distro_codename}-security"
  - "${distro_id}:${distro_codename}-updates"

unattended_upgrades_auto_fix_interrupted_dpkg: true
unattended_upgrades_minimal_steps: true
unattended_upgrades_install_on_shutdown: false
unattended_upgrades_mail: "root"
unattended_upgrades_remove_unused_kernel_packages: true
unattended_upgrades_remove_unused_dependencies: true
unattended_upgrades_automatic_reboot: true
unattended_upgrades_automatic_reboot_time: "04:00"

# Daily update configuration (20auto-upgrades)
unattended_upgrades_update_package_lists: 1
unattended_upgrades_download_upgradeable_packages: 1
unattended_upgrades_autoclean_interval: 7
unattended_upgrades_unattended_upgrade: 1
