---
- name: Manage A record
  sbarbett.pihole.local_a_record:
    host: "{{ inventory_hostname }}"
    ip: "{{ proxmox_net0.ip.split('/')[0] }}"
    state: "present"
    url: "{{ pihole_instance.name }}"
    password: "{{ pihole_instance.password }}"
  when: proxmox_net0.ip is defined

- name: Manage AAAA record
  sbarbett.pihole.local_aaaa_record:
    host: "{{ inventory_hostname }}"
    ip: "{{ proxmox_net0.ip6.split('/')[0] }}"
    state: "present"
    url: "{{ pihole_instance.name }}"
    password: "{{ pihole_instance.password }}"
  when: proxmox_net0.ip6 is defined
