---
ktn_version: "v2.0.9"
ktn_repository: "https://github.com/leafac/kill-the-newsletter.git"
ktn_user: "kill-the-newsletter"
ktn_group: "kill-the-newsletter"
ktn_root: "/opt/kill-the-newsletter"
ktn_data_directory: "/var/lib/kill-the-newsletter/data"
ktn_hostname: "ktn-lxc-01.van-bee.ts.net"
ktn_smtp_port: 2525
ktn_http_port: 8088
