download_url: https://galaxy.ansible.com/api/v3/plugin/ansible/content/published/collections/artifacts/sbarbett-pihole-1.1.1.tar.gz
format_version: 1.0.0
name: pihole
namespace: sbarbett
server: https://galaxy.ansible.com/api/
signatures: []
version: 1.1.1
version_url: /api/v3/plugin/ansible/content/published/collections/index/sbarbett/pihole/versions/1.1.1/
