- name: Install basic workstation software
  hosts: debian  # Replace 'debian' with your target host group
  become: true
  tasks:
    - name: Install vlc package
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - vlc
